corpus = [
    "The quick brown fox jumps over the lazy dog",
    "I love natural language processing and deep learning",
    "Machine learning is a subfield of artificial intelligence",
    "Neural networks can approximate complex functions",
    "Python is widely used for data science and AI",
    "Statistics and probability form the basis of machine learning",
    "Optimization is crucial for training deep models",
    "Backpropagation is used to compute gradients efficiently",
    "Word embeddings capture semantic meaning in vector space",
    "Text data is often represented as numerical features",
    "Convolutional neural networks are good for image recognition",
    "Recurrent neural networks process sequential information",
    "Transformers are state of the art in NLP",
    "Attention mechanisms allow models to focus on relevant words",
    "Large language models can generate human-like text",
    "Tokenization splits text into smaller units",
    "Stemming and lemmatization reduce words to their base forms",
    "Stopwords like 'the' and 'is' often add little meaning",
    "TF-IDF reduces the weight of common words in documents",
    "Word2Vec and GloVe are popular embedding techniques",
]